Replace remaining occurrences of ambiguous 'byte' type with 'BYTE'
The use of 'byte' causes compilation to fail in MSVC 2019:

N:\Documenten\Projecten\Other\windows_thunks\include\thunks.hpp(57,35): error C2872: 'byte': ambiguous symbol
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\rpcndr.h(191,23): message : could be 'unsigned char byte'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\cstddef(29,12): message : or       'std::byte'